require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Inspection' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  pod 'react-native-nfc-manager', :path => '../node_modules/react-native-nfc-manager'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'


  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'


  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'InspectionTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Inspection-tvOS' do
  # Pods for Inspection-tvOS

  target 'Inspection-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
